version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:v1.8.2
    ports:
      - "9100:9100"
    networks:
      - monitoring
    restart: unless-stopped

  loki:
    image: grafana/loki:3.1.1
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
      - ./tenant-limits.yaml:/etc/loki/tenant-limits.yaml
      - loki_data:/loki
    command:
      - -config.file=/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    networks:
      - monitoring
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2'
    environment:
      - LOKI_LIMITS_INGESTION_RATE_BYTES=10485760
      - LOKI_LIMITS_INGESTION_BURST_SIZE_BYTES=15728640

  promtail:
    image: grafana/promtail:3.1.1
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - monitoring
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.58
    ports:
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.2.0
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  loki_data:
  grafana_data:
