global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'jaeger'
    scrape_interval: 5s
    static_configs:
      - targets: ['jaeger:14269']

  # Thêm các service khác cần giám sát
  - job_name: 'application_services'
    static_configs:
      - targets: ['your-service:port']